import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Aakash',
            email: 'aliakber@yahoomail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'Sadia',
            email: 'sadia@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products:[
        {
            name: 'Owl Pandant/Necklace',
            category: 'Necklace',
            image: '/images/p1.jpg',
            price: '180',
            countInStock: 21,
            brand: 'Aliexpress',
            rating: 4.5,
            numReviews: 12,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Crown Shape Ring',
            category: 'Ring',
            image: '/images/p2.jpg',
            price: '80',
            countInStock: 17,
            brand: 'Aliexpress',
            rating: 4.6,
            numReviews: 15,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Antique Pocket Watch',
            category: 'Watch',
            image: '/images/p3.jpg',
            price: '300',
            countInStock: 9,
            brand: 'Aliexpress',
            rating: 4.4,
            numReviews: 16,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Pandent Earring',
            category: 'Earrings',
            image: '/images/p4.jpg',
            price: '140',
            countInStock: 52,
            brand: 'Aliexpress',
            rating: 4.7,
            numReviews: 38,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Vintage Hand Band',
            category: 'Band',
            image: '/images/p5.jpg',
            price: '70',
            countInStock: 25,
            brand: 'Aliexpress',
            rating: 4.3,
            numReviews: 21,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Single Wing Pandent/Necklace',
            category: 'Necklace',
            image: '/images/p6.jpg',
            price: '150',
            countInStock: 8,
            brand: 'Aliexpress',
            rating: 3.9,
            numReviews: 14,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Crystal Solid Ring Set',
            category: 'Ring',
            image: '/images/p7.jpg',
            price: '400',
            countInStock: 15,
            brand: 'Aliexpress',
            rating: 4.5,
            numReviews: 19,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Multiple Ring Set',
            category: 'Ring',
            image: '/images/p8.jpg',
            price: '150',
            countInStock: 1,
            brand: 'Aliexpress',
            rating: 4.3,
            numReviews: 16,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'White Crytal Earring Set',
            category: 'Earring',
            image: '/images/p9.jpg',
            price: '370',
            countInStock: 2,
            brand: 'Aliexpress',
            rating: 4.2,
            numReviews: 12,
            description: 'Beautiful and heavy metal made product',
        },
        {
            name: 'Crystal & Round Necklace',
            category: 'Necklace',
            image: '/images/p10.jpg',
            price: '320',
            countInStock: 0,
            brand: 'Aliexpress',
            rating: 3.9,
            numReviews: 7,
            description: 'Beautiful and heavy metal made product',
        },
    ],
};
export default data;